name: ecommerce
description: "This is a new flutter project for an ecommerce App."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'


#--------------- PACKAGES----------------#
dependencies:
  path_provider_android: ^2.2.14
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.20.0
  logger: ^2.0.0
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.13.0


  #------------------ ./ PACKAGES END -------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  #------------------- LOCAL ASSETS -----------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/

  #------------------- LOCAL FONTS -----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800 